# Copy this file to app-config.local.yaml to override default app settings.
# Example with GitHub integration referencing external secrets file.

# integrations:
#   github:
#     - host: github.com
#       apps:
#         - $include: ../extra-files/github-app-credentials.yaml

app:
  title: Red Hat Developer Hub
  baseUrl: ${BASE_URL}
  branding:
    # If using a different logo, replace these lines with your own image(s)
    # fullLogo: data:image/svg+xml;base64,your-image-goes-here==
    # - or -
    # fullLogo:
    #   dark: data:image/svg+xml;base64,your-image-in-dark-mode-goes-here==
    #   light: data:image/svg+xml;base64,your-image-in-light-mode-goes-here==
    # iconLogo: data:image/svg+xml;base64,your-image-goes-here==
    fullLogoWidth: ${FULL_LOGO_WIDTH}
    theme:
      light:
        palette:
          primary:
            main: ${PRIMARY_LIGHT_COLOR}
          navigation:
            indicator: ${NAV_INDICATOR_LIGHT_COLOR}
        pageTheme:
          default:
            backgroundColor:
              - ${HEADER_LIGHT_COLOR_1}
              - ${HEADER_LIGHT_COLOR_2}
      dark:
        palette:
          primary:
            main: ${PRIMARY_DARK_COLOR}
          navigation:
            indicator: ${NAV_INDICATOR_DARK_COLOR}
        pageTheme:
          default:
            backgroundColor:
              - ${HEADER_DARK_COLOR_1}
              - ${HEADER_DARK_COLOR_2}

# Tech Radar Plugin Example - uncomment with plugin override to use
# Replace URL with your own hosted json to visualize data in Tech Radar
# techRadar:
#   url: https://raw.githubusercontent.com/backstage/community-plugins/main/workspaces/tech-radar/plugins/tech-radar-common/src/sampleTechRadarResponse.json
