# This is the default dynamic plugins config, and any user configuration should be added dynamic-plugins.override.yaml instead
includes:
  - dynamic-plugins.default.yaml
  # Writable path in the init container for extensions plugin configuration.
  - /dynamic-plugins-root/dynamic-plugins.extensions.yaml

plugins:
  # Tech Radar frontend plugin
  - package: 'oci://quay.io/rhdh/backstage-community-plugin-tech-radar:{{inherit}}'
    disabled: false

  # Quay plugin
  - package: 'oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-quay-backend:bs_1.52.0__1.17.0'
    disabled: false

  # Scaffolder Github plugin - used by Dynamic Plugin Software Templates
  - package: 'oci://quay.io/rhdh/backstage-plugin-scaffolder-backend-module-github:{{inherit}}'
    disabled: false

  #########################################################
  # Enable dynamic plugins installation by using Extensions
  #########################################################

  # TODO: we may need to update this ref
  - package: 'oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-extensions:bs_1.52.0__0.19.1'
    disabled: false

  # TODO: we may need to update this ref
  - package: 'oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-extensions-backend:bs_1.52.0__0.19.1'
    disabled: false
    pluginConfig:
      extensions:
        installation:
          enabled: true
          saveToSingleFile:
            # NOTE: the path needs to be writable by the main RHDH container user
            file: /opt/app-root/src/dynamic-plugins-root/dynamic-plugins.extensions.yaml
  ########## End Extensions #################################

  #########################################################
  # Developer Lightspeed plugins
  #########################################################

  # Lightspeed frontend plugin
  # TODO: re-enable this once the catalog index is stabilized
  - package: 'oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-lightspeed:{{inherit}}'
    disabled: true

  # Lightspeed backend plugin
  # TODO: re-enable this once the catalog index is stabilized
  - package: 'oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-lightspeed-backend:{{inherit}}'
    disabled: true
