# This is the default dynamic plugins config, and any user configuration should be added dynamic-plugins.override.yaml instead
includes:
  - dynamic-plugins.default.yaml
  # Writable path in the init container for extensions plugin configuration.
  - /dynamic-plugins-root/dynamic-plugins.extensions.yaml

plugins:
  # Tech Radar frontend plugin
# # TODO: Replace the `./dynamic-plugins/dist/` path with the OCI reference once we switch to that in the dynamic-plugins.default.yaml (DPDY) file in the catalog index image - see https://issues.redhat.com/browse/RHDHPLAN-934 and https://issues.redhat.com/browse/RHDHPLAN-256
  # - package: 'oci://quay.io/rhdh/backstage-community-plugin-tech-radar:{{inherit}}'
  - package: ./dynamic-plugins/dist/backstage-community-plugin-tech-radar
    disabled: false

  # Quay plugin
  - package: 'oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-quay-backend:{{inherit}}'
    disabled: false

  # Scaffolder Github plugin - used by Dynamic Plugin Software Templates
  - package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic
    disabled: false

  # Floating Action Button plugin with submenu actions
  # TODO: This plugin will be removed in RHDH 2.1 (https://redhat.atlassian.net/browse/RHDHPLAN-1006)
  # - package: 'oci://quay.io/rhdh/red-hat-developer-hub-backstage-plugin-global-floating-action-button:{{inherit}}'
  - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-global-floating-action-button
    disabled: true # disabled as conflicts with Lightspeed FAB, will be deprecated / removed.

  #########################################################
  # Enable dynamic plugins installation by using Extensions
  #########################################################

  # TODO: Replace the `./dynamic-plugins/dist/` path with the OCI reference once we switch to that in the dynamic-plugins.default.yaml (DPDY) file in the catalog index image - see https://issues.redhat.com/browse/RHDHPLAN-934 and https://issues.redhat.com/browse/RHDHPLAN-256
  # - package: 'oci://quay.io/rhdh/red-hat-developer-hub-backstage-plugin-extensions:{{inherit}}'
  - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-extensions
    disabled: false

  # TODO: Replace the `./dynamic-plugins/dist/` path with the OCI reference once we switch to that in the dynamic-plugins.default.yaml (DPDY) file in the catalog index image - see https://issues.redhat.com/browse/RHDHPLAN-934 and https://issues.redhat.com/browse/RHDHPLAN-256
  # - package: 'oci://quay.io/rhdh/red-hat-developer-hub-backstage-plugin-extensions-backend:{{inherit}}'
  - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-extensions-backend-dynamic
    disabled: false
    pluginConfig:
      extensions:
        installation:
          enabled: true
          saveToSingleFile:
            # NOTE: the path needs to be writable by the main RHDH container user
            file: /opt/app-root/src/dynamic-plugins-root/dynamic-plugins.extensions.yaml
  ########## End Extensions #################################

  #########################################################
  # Developer Lightspeed plugins
  #########################################################

  # Lightspeed frontend plugin
  - package: 'oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-lightspeed:{{inherit}}'
    disabled: false

  # Lightspeed backend plugin
  - package: 'oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-lightspeed-backend:{{inherit}}'
    disabled: false
