name: PR TOML Validator

on:
  push:
    paths:
      - '**.toml'
  pull_request:
    paths:
      - '**.toml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: tombi-toml/setup-tombi@9fdb1f12707aafdc140839c60421336d4ae157ea # v1.2.6
        with:
          version: 'v0.9.9'
          checksum: 'b50dbc90ec27591dbaf564b628bd3b3e4ead371a60931bc8ea5f34d7cd1d3607'
      - name: Validate TOML files
        run: tombi lint
